### ISSUE TITLE
Discord Action Bars

### ISSUE THREAD

**Issue by Colaire** [UndercityAddons-Vanilla/MacroTT-V#2]
Hi, this great Addon, doesn't work with Discord Action Bars / DAB.
Is it possible to make it working?

**Comment by ice-92** [comment]
Can confirm this doesn't work.

**Comment by fulzamoth** [comment]
Adding support for DAB would not be an easy task without rewriting how DAB handles tooltips. DAB does not have a hook for setting tooltip text, not is getting the current DAB button, and doesn't call the default UI Actionbar_SetTooltip function.
